# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-15 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('empid', models.BigIntegerField(blank=True, db_column='EmpId', null=True)),
                ('deptcode', models.IntegerField(blank=True, db_column='DeptCode', null=True)),
                ('managercode', models.BigIntegerField(blank=True, db_column='ManagerCode', null=True)),
                ('taskdesc', models.CharField(blank=True, db_column='TaskDesc', max_length=255, null=True)),
                ('tasktype', models.CharField(blank=True, db_column='TaskType', max_length=45, null=True)),
                ('duration', models.IntegerField(blank=True, db_column='Duration', null=True)),
                ('createddate', models.DateField(blank=True, db_column='CreatedDate', null=True)),
                ('editedate', models.DateField(blank=True, db_column='EditeDate', null=True)),
                ('ifsubmitted', models.IntegerField(blank=True, db_column='IfSubmitted', null=True)),
            ],
            options={
                'db_table': 'sheet',
                'managed': False,
            },
        ),
    ]
