# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_sheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet1',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('deptcode', models.IntegerField(blank=True, db_column='DeptCode', null=True)),
                ('managercode', models.BigIntegerField(blank=True, db_column='ManagerCode', null=True)),
                ('managerlevel2', models.BigIntegerField(blank=True, db_column='ManagerLevel2', null=True)),
                ('managerlevel3', models.BigIntegerField(blank=True, db_column='ManagerLevel3', null=True)),
                ('managerlevel4', models.BigIntegerField(blank=True, db_column='ManagerLevel4', null=True)),
                ('taskdesc', models.CharField(blank=True, db_column='TaskDesc', max_length=255, null=True, verbose_name='Task Descreption')),
                ('tasktype', models.CharField(blank=True, choices=[('m', 'Master'), ('h', 'Help')], db_column='TaskType', max_length=1, null=True, verbose_name='Task type')),
                ('duration', models.IntegerField(blank=True, db_column='Duration', null=True, verbose_name='Duration')),
                ('createddate', models.DateField(blank=True, db_column='CreatedDate', null=True)),
                ('taskdate', models.DateField(blank=True, db_column='TaskDate', null=True, verbose_name='task date')),
                ('editedate', models.DateField(blank=True, db_column='EditeDate', null=True)),
                ('ifsubmitted', models.IntegerField(blank=True, db_column='IfSubmitted', null=True)),
            ],
            options={
                'db_table': 'sheet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee1',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('empid', models.CharField(blank=True, db_column='EmpId', max_length=45, null=True, unique=True)),
                ('empname', models.CharField(blank=True, db_column='EmpName', max_length=255, null=True)),
                ('deptcode', models.CharField(blank=True, db_column='DeptCode', max_length=45, null=True)),
                ('deptname', models.CharField(blank=True, db_column='DeptName', max_length=200, null=True)),
                ('ismanager', models.IntegerField(blank=True, db_column='IsManager', null=True)),
                ('ext', models.CharField(blank=True, db_column='Ext', max_length=45, null=True)),
                ('mobile', models.CharField(blank=True, db_column='Mobile', max_length=45, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('jobtitle', models.CharField(blank=True, db_column='JobTitle', max_length=200, null=True)),
                ('managercode', models.BigIntegerField(blank=True, db_column='ManagerCode', null=True)),
            ],
        ),
    ]
