# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-14 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20171210_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('projecid', models.IntegerField(blank=True, null=True)),
                ('taskid', models.IntegerField(blank=True, null=True)),
                ('filename', models.CharField(blank=True, max_length=100)),
                ('managerlevel2', models.BigIntegerField(blank=True, db_column='ManagerLevel2', null=True)),
            ],
        ),
    ]
