# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-14 06:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20171214_0919'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='media',
            table='media',
        ),
    ]
