# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-14 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20171214_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='projecid',
            new_name='projectid',
        ),
    ]
