# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-15 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20171214_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='progress',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='cancelledby',
            field=models.IntegerField(blank=True, db_column='CancelledBy', null=True),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='desc',
            field=models.CharField(db_column='Desc', max_length=2500),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='name',
            field=models.CharField(db_column='Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='filepath',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Files Upload'),
        ),
    ]
