# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-16 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20171216_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='progress',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='status',
            field=models.CharField(choices=[('', 'Choice action'), ('New', 'New'), ('InProgress', 'InProgress'), ('Done', 'Done'), ('Hold', 'Hold'), ('Cancelled', 'Cancelled'), ('Closed', 'Closed')], db_column='Status', max_length=10),
        ),
    ]
