# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_historicaltask_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('deptauthcode', models.CharField(blank=True, db_column='DeptAuthCode', max_length=10, null=True)),
                ('start', models.DateTimeField(blank=True, db_column='Start', null=True)),
                ('end', models.DateTimeField(blank=True, db_column='End', null=True)),
                ('expired', models.CharField(blank=True, db_column='Expired', max_length=1, null=True)),
            ],
            options={
                'db_table': 'delegation',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='departementid',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='projectid',
        ),
        migrations.RemoveField(
            model_name='media',
            name='projectid',
        ),
        migrations.RemoveField(
            model_name='media',
            name='taskid',
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='departement',
            field=models.ForeignKey(blank=True, db_column='departementid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.Department', to_field='deptcode'),
        ),
        migrations.AddField(
            model_name='media',
            name='project',
            field=models.ForeignKey(blank=True, db_column='projectid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Project'),
        ),
        migrations.AddField(
            model_name='media',
            name='task',
            field=models.ForeignKey(blank=True, db_column='taskid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Task'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='assignedto',
            field=models.ForeignKey(blank=True, db_column='assignedto', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.Employee', to_field='empid'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='createdby',
            field=models.ForeignKey(blank=True, db_column='CreatedBy', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.Employee', to_field='empid'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='project',
            field=models.ForeignKey(blank=True, db_column='projectid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.Project'),
        ),
    ]
